version: '3'
services:
  postgres:
    image: "postgres:12.8"
    container_name: "omnivore-postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=omnivore
      - PG_POOL_MAX=20
    healthcheck:
      test: "exit 0"
      interval: 2s
      timeout: 12s
      retries: 3
    expose:
      - 5432

  migrate:
    build:
      context: .
      dockerfile: ./packages/db/Dockerfile
    container_name: "omnivore-migrate"
    command: '/bin/sh ./packages/db/setup.sh'
    environment:
      - PGPASSWORD=postgres
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=omnivore
      - ES_URL=http://elastic:9200
      - ES_USERNAME=blank
      - ES_PASSWORD=blank
    depends_on:
      postgres:
        condition: service_healthy

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: "omnivore-elastic"
    healthcheck:
      test: curl 0.0.0.0:9200/_cat/health >/dev/null || exit 1
      interval: 2s
      timeout: 2s
      retries: 5
    environment:
      - discovery.type=single-node
      - http.cors.allow-origin=*
      - http.cors.enabled=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    volumes:
      - ./.docker/elastic-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  api-test:
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile-test
    container_name: "omnivore-api-test"
    environment:
      - API_ENV=local
      - PG_HOST=postgres
      - PG_USER=app_user
      - PG_PASSWORD=app_pass
      - PG_DB=omnivore
      - PG_PORT=5432
      - PG_POOL_MAX=20
      - ELASTIC_URL=http://elastic:9200
      - IMAGE_PROXY_URL=http://localhost:9999
      - IMAGE_PROXY_SECRET=some-secret
      - JWT_SECRET=some_secret
      - SSO_JWT_SECRET=some_sso_secret
      - CLIENT_URL=http://localhost:3000
      - GATEWAY_URL=http://localhost:8080/api
      - PUPPETEER_TASK_HANDLER_URL=http://localhost:9090/
      - REMINDER_TASK_HANDLER_URL=/svc/reminders/trigger
      - BOOKMARKLET_JWT_SECRET=some_bookmarklet_secret
      - BOOKMARKLET_VERSION=1.0.0
      - PREVIEW_IMAGE_WRAPPER_ID='selected_highlight_wrapper'
      - GCP_PROJECT_ID=omnivore-local
      - GAUTH_CLIENT_ID='notset'
      - GAUTH_SECRET='notset'
      - SEGMENT_WRITE_KEY='test'
    depends_on:
      migrate:
        condition: service_completed_successfully
      elastic:
        condition: service_healthy
